# Generated by Django 6.0.1 on 2026-01-12 13:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedAddressPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("street1", models.CharField(max_length=200)),
                ("street2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="SavedPackagePreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weight_oz", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "length_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "width_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "height_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("external_order_number", models.CharField(blank=True, max_length=100)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("from_name", models.CharField(blank=True, max_length=200)),
                ("from_company", models.CharField(blank=True, max_length=200)),
                ("from_street1", models.CharField(blank=True, max_length=200)),
                ("from_street2", models.CharField(blank=True, max_length=200)),
                ("from_city", models.CharField(blank=True, max_length=100)),
                ("from_state", models.CharField(blank=True, max_length=2)),
                ("from_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "from_country",
                    models.CharField(blank=True, default="US", max_length=2),
                ),
                ("to_name", models.CharField(blank=True, max_length=200)),
                ("to_company", models.CharField(blank=True, max_length=200)),
                ("to_street1", models.CharField(blank=True, max_length=200)),
                ("to_street2", models.CharField(blank=True, max_length=200)),
                ("to_city", models.CharField(blank=True, max_length=100)),
                ("to_state", models.CharField(blank=True, max_length=2)),
                ("to_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "to_country",
                    models.CharField(blank=True, default="US", max_length=2),
                ),
                (
                    "weight_oz",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "length_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "width_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "height_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("NEEDS_INFO", "Needs info"),
                            ("INVALID", "Invalid"),
                            ("READY", "Ready"),
                        ],
                        default="NEEDS_INFO",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                (
                    "address_verification_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("VALID", "Valid"),
                            ("CORRECTED", "Corrected"),
                            ("INVALID", "Invalid"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "address_verification_details",
                    models.JSONField(blank=True, default=dict),
                ),
                ("selected_service", models.CharField(blank=True, max_length=100)),
                (
                    "selected_service_price_cents",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "label_status",
                    models.CharField(
                        choices=[
                            ("NOT_PURCHASED", "Not purchased"),
                            ("PURCHASED", "Purchased"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_PURCHASED",
                        max_length=20,
                    ),
                ),
                ("label_url", models.URLField(blank=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="imports.importjob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["import_job", "row_number"],
                        name="shipments_s_import__fe464b_idx",
                    ),
                    models.Index(
                        fields=["import_job", "validation_status"],
                        name="shipments_s_import__e428c0_idx",
                    ),
                ],
            },
        ),
    ]
